AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  me2resh-daily
  Daily executive intelligence scan that aggregates platform, architecture, and security updates

Parameters:
  ToEmailAddress:
    Type: String
    Description: Email address to send daily reports to
    Default: ""

  FromEmailAddress:
    Type: String
    Description: Verified SES email address to send from
    Default: ""

  OpenAIApiKey:
    Type: String
    Description: OpenAI API key for ChatGPT analysis
    NoEcho: true

  ScheduleExpression:
    Type: String
    Description: EventBridge Scheduler/CloudWatch Events expression (default 05:00 Europe/London)
    # Keep this quoted so '?' survives shells/CI.
    Default: "cron(0 5 * * ? *)"
    # IMPORTANT: Use single quotes and single backslashes for CloudFormation regex.
    AllowedPattern: '^((rate\(\d+ (minute|minutes|hour|hours|day|days)\))|(cron\([^)]+\)))$'

Globals:
  Function:
    Timeout: 900
    Tracing: Active
    MemorySize: 512
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        TO_EMAIL_ADDRESS: !Ref ToEmailAddress
        FROM_EMAIL_ADDRESS: !Ref FromEmailAddress
        OPENAI_API_KEY: !Ref OpenAIApiKey

Resources:
  DailyScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: daily-scan.lambdaHandler
      Description: Performs daily scan of platform and architecture sources
      Policies:
        - SESCrudPolicy:
            IdentityName: !Ref FromEmailAddress
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
      Events:
        DailySchedule:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: !Ref ScheduleExpression
            ScheduleExpressionTimezone: Europe/London
            FlexibleTimeWindow:
              Mode: "OFF"            # must be quoted in YAML 1.1
            Name: Me2reshDailyScanSchedule
            Description: Triggers daily scan at 05:00 Europe/London
            State: ENABLED
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - src/command/lambda/daily-scan.ts
        External:
          - '@aws-sdk/*'

Outputs:
  DailyScanFunction:
    Description: Daily Scan Lambda Function ARN
    Value: !GetAtt DailyScanFunction.Arn

  DailyScanFunctionRole:
    Description: IAM Role created for Daily Scan function
    Value: !GetAtt DailyScanFunctionRole.Arn

  ScheduleExpressionOut:
    Description: EventBridge Scheduler expression in use
    Value: !Ref ScheduleExpression