# Me2resh Daily Intel Scan - Source Configuration
# This file defines all sources to scan, organized by topic

email:
  to_address: "${TO_EMAIL_ADDRESS}"  # Set via environment variable (ahmed.abdelaliem@gmail.com)
  from_address: "${FROM_EMAIL_ADDRESS}"  # Set via environment variable
  subject_prefix: "Platform & Architecture Daily"

scan_config:
  timezone: "Europe/London"
  scan_time: "05:00"
  lookback_hours: 72  # How far back to look for new items

topics:
  # 1. FHIR / HL7 / Interoperability Standards & UK Policy
  - name: "FHIR and HL7 Standards"
    category: "standards"
    priority: 2
    sources:
      - name: "HL7 Official Blog"
        url: "https://blog.hl7.org/"
        type: "rss"
        keywords: ["ballot", "implementation guide", "AI", "governance"]

      - name: "HL7 News Publication"
        url: "https://hl7news.hl7.org/"
        type: "rss"
        keywords: ["event", "program", "update"]

      - name: "FHIR Foundation"
        url: "https://fhir.org/"
        type: "html"
        keywords: ["community", "standard", "specification"]

      - name: "NHS Digital FHIR APIs"
        url: "https://digital.nhs.uk/services/fhir-apis"
        type: "html"
        keywords: ["API", "FHIR", "NHS"]

      - name: "NHS England Interoperability"
        url: "https://www.england.nhs.uk/long-read/interoperability/"
        type: "html"
        keywords: ["interoperability", "data sharing"]

      - name: "ONC Health IT Blog"
        url: "https://www.healthit.gov/buzz-blog/"
        type: "rss"
        keywords: ["TEFCA", "FHIR", "exchange"]

      - name: "CMS FHIR Spotlight"
        url: "https://www.cms.gov/priorities/burden-reduction/overview/spotlight"
        type: "html"
        keywords: ["FHIR", "interoperability"]

      - name: "HL7 UK Blog"
        url: "https://www.hl7.org.uk/category/blog/"
        type: "rss"
        keywords: ["UK", "implementation", "case study"]

  # 2. AI in Healthcare & Clinical Pathways
  - name: "AI in Healthcare"
    category: "ai_healthcare"
    priority: 1  # Highest priority
    sources:
      - name: "NEJM AI"
        url: "https://ai.nejm.org/"
        type: "rss"
        keywords: ["clinical AI", "safety", "deployment", "methods", "policy"]

      - name: "npj Digital Medicine"
        url: "https://www.nature.com/npjdigitalmed/"
        type: "rss"
        keywords: ["implementation", "pathways", "diagnostics", "AI"]

      - name: "Lancet Digital Health"
        url: "https://www.thelancet.com/journals/landig/home"
        type: "rss"
        rss_url: "https://www.thelancet.com/content/rss"
        keywords: ["digital health", "AI", "practice"]

      - name: "FDA AI/ML SaMD"
        url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-and-machine-learning-software-medical-device"
        type: "html"
        keywords: ["AI", "ML", "lifecycle", "marketing", "submission"]

      - name: "MHRA Software & AI Medical Device"
        url: "https://www.gov.uk/government/publications/software-and-artificial-intelligence-ai-as-a-medical-device/software-and-artificial-intelligence-ai-as-a-medical-device"
        type: "html"
        keywords: ["UK", "guidance", "SaMD"]

      - name: "EU AI Act Timeline"
        url: "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai"
        type: "html"
        keywords: ["AI Act", "regulation", "GPAI", "high-risk", "medical"]

  # 3. General AI & Platform
  - name: "General AI & Platform"
    category: "ai_platform"
    priority: 1
    sources:
      - name: "TLDR Tech AI"
        url: "https://tldr.tech/"
        type: "rss"
        keywords: ["AI", "tooling", "platform"]

      - name: "Hugging Face Blog"
        url: "https://huggingface.co/blog"
        type: "rss"
        keywords: ["AI", "models", "infrastructure"]

      - name: "AWS Bedrock Blog"
        url: "https://aws.amazon.com/blogs/machine-learning/"
        type: "rss"
        keywords: ["Bedrock", "AI", "AWS"]

  # 4. Corporate Intelligence - Hims & Hers
  - name: "Hims & Hers Corporate"
    category: "corporate"
    priority: 3
    sources:
      - name: "Hims & Hers Investor Relations"
        url: "https://investors.hims.com/news/default.aspx"
        type: "html"
        keywords: ["earnings", "financial", "results"]

      - name: "Hims & Hers Newsroom"
        url: "https://news.hims.com/"
        type: "html"
        keywords: ["product", "launch", "strategy"]

      - name: "SEC EDGAR Filings"
        url: "https://www.sec.gov/edgar/search/#/entityName=Hims%20&%20Hers%20Health,%20Inc."
        type: "html"
        cik: "0001773751"
        keywords: ["10-K", "10-Q", "8-K", "filing"]

  # 5. AWS & Platform Engineering
  - name: "AWS Platform"
    category: "aws_platform"
    priority: 1
    sources:
      - name: "AWS What's New"
        url: "https://aws.amazon.com/new/"
        type: "rss"
        keywords: ["Lambda", "API Gateway", "EventBridge", "Step Functions", "DynamoDB"]

      - name: "AWS Security Bulletins"
        url: "https://aws.amazon.com/security/security-bulletins/"
        type: "rss"
        keywords: ["security", "vulnerability", "bulletin"]

      - name: "Amazon Linux Security (ALAS)"
        url: "https://alas.aws.amazon.com/"
        type: "rss"
        keywords: ["security", "update", "AL2", "AL2023"]

      - name: "AWS Compute Blog"
        url: "https://aws.amazon.com/blogs/compute/"
        type: "rss"
        keywords: ["Lambda", "serverless", "compute"]

      - name: "AWS Architecture Blog"
        url: "https://aws.amazon.com/blogs/architecture/"
        type: "rss"
        keywords: ["architecture", "well-architected", "patterns"]

      - name: "CNCF Blog"
        url: "https://www.cncf.io/blog/"
        type: "rss"
        keywords: ["Kubernetes", "cloud native", "serverless"]

      - name: "Backstage Blog (Spotify)"
        url: "https://backstage.spotify.com/discover/blog/"
        type: "rss"
        keywords: ["developer portal", "platform", "DX"]

      - name: "Backstage.io Blog"
        url: "https://backstage.io/blog/"
        type: "rss"
        keywords: ["developer experience", "platform"]

  # 6. Language & Framework Releases
  - name: "Stack Releases"
    category: "releases"
    priority: 2
    sources:
      - name: "NestJS Releases"
        url: "https://github.com/nestjs/nest/releases"
        type: "github_releases"
        keywords: ["release", "breaking", "feature"]

      - name: "TypeScript Releases"
        url: "https://github.com/microsoft/TypeScript/releases"
        type: "github_releases"
        keywords: ["release", "breaking", "feature"]

      - name: "Golang Blog"
        url: "https://go.dev/blog/"
        type: "rss"
        keywords: ["release", "version"]

      - name: "AWS SAM CLI Releases"
        url: "https://github.com/aws/aws-sam-cli/releases"
        type: "github_releases"
        keywords: ["release", "feature"]

      - name: "AWS SAM Spec Releases"
        url: "https://github.com/aws/serverless-application-model/releases"
        type: "github_releases"
        keywords: ["specification", "release"]

      - name: "PHP Security Advisories"
        url: "https://github.com/php/php-src/security/advisories"
        type: "github_advisories"
        keywords: ["security", "vulnerability"]

  # 7. Security Advisories
  - name: "Security Advisories"
    category: "security"
    priority: 1
    sources:
      - name: "NVD (National Vulnerability Database)"
        url: "https://nvd.nist.gov/vuln"
        type: "nvd_api"
        filter: ["npm", "golang", "php", "aws"]
        keywords: ["CVE", "vulnerability"]

      - name: "CISA Known Exploited Vulnerabilities"
        url: "https://www.cisa.gov/known-exploited-vulnerabilities-catalog"
        type: "cisa_api"
        keywords: ["exploited", "vulnerability"]

      - name: "GitHub Advisory Database"
        url: "https://github.com/advisories"
        type: "github_advisories"
        ecosystems: ["npm", "composer", "go"]
        keywords: ["advisory", "security"]

  # 8. Developer Experience & Trends
  - name: "Developer Experience"
    category: "developer_experience"
    priority: 3
    sources:
      - name: "InfoQ"
        url: "https://www.infoq.com/news/"
        type: "rss"
        keywords: ["architecture", "platform", "DevOps"]

      - name: "The New Stack"
        url: "https://thenewstack.io/rss-feeds/"
        type: "rss"
        keywords: ["cloud native", "platform", "DX"]

      - name: "ThoughtWorks Tech Radar"
        url: "https://www.thoughtworks.com/radar"
        type: "html"
        keywords: ["radar", "trends", "adopt", "trial"]

      - name: "Golang Weekly"
        url: "https://golangweekly.com/"
        type: "rss"
        keywords: ["golang", "library", "tool"]

      - name: "TypeScript Weekly"
        url: "https://typescript-weekly.com/"
        type: "rss"
        keywords: ["typescript", "library", "pattern"]

# Severity rules for automatic classification
severity_rules:
  high:
    - "compliance deadline"
    - "regulatory obligation"
    - "breaking change"
    - "exploited vulnerability"
    - "critical security"
    - "AWS service deprecation"
    - "major cost impact"

  medium:
    - "new feature"
    - "ecosystem shift"
    - "version upgrade"
    - "recommended update"

  low:
    - "advisory"
    - "background trend"
    - "minor update"

# Impact mapping keywords
impact_keywords:
  Regulatory:
    - "compliance"
    - "regulation"
    - "GDPR"
    - "HIPAA"
    - "FDA"
    - "MHRA"
    - "AI Act"

  Platform:
    - "AWS"
    - "Lambda"
    - "architecture"
    - "infrastructure"
    - "deployment"

  Security:
    - "CVE"
    - "vulnerability"
    - "security"
    - "exploit"
    - "patch"

  DX:
    - "developer experience"
    - "tooling"
    - "productivity"
    - "workflow"

  Cost:
    - "pricing"
    - "cost"
    - "optimization"
    - "savings"

  "Org/Strategy":
    - "strategy"
    - "organizational"
    - "M&A"
    - "earnings"
