# ============================================================================
# ME2RESH DAILY - UNIFIED SOURCE CONFIGURATION
# ============================================================================
# All research categories, sources, weights, priorities, and search strategies
# in a single unified configuration structure.
#
# Configuration parameters at top, categories below.
# ============================================================================

# ----------------------------------------------------------------------------
# GLOBAL CONFIGURATION (Flat structure for compatibility)
# ----------------------------------------------------------------------------
email:
  to_address: "${TO_EMAIL_ADDRESS}"
  from_address: "${FROM_EMAIL_ADDRESS}"
  subject_prefix: "Me2resh Daily"

scan_config:
  timezone: "Europe/London"
  scan_time: "05:00"
  lookback_hours: 72  # Increased to 72h to ensure finding non-AWS content
  max_items_per_source: 20
  enable_perplexity_research: true

# Legacy topics array (keep for backwards compatibility)
topics: []

# ----------------------------------------------------------------------------
# RESEARCH CATEGORIES
# ----------------------------------------------------------------------------
# Each category defines:
#   - priority: 1-5 (1 = highest, drives search order and top_signals selection)
#   - weight: Relative importance for ranking within category
#   - max_items: Category-specific cap (overrides global if set)
#   - output_section: Where items go in final JSON
#   - search_strategy: How Perplexity should search for this category
#   - sources: List of authoritative sources to prioritize
#   - extract: What specific information to look for
#   - keywords: Boost these terms in matching/ranking
# ----------------------------------------------------------------------------

categories:
  # ==========================================================================
  # 1. SECURITY & VULNERABILITIES (Highest Priority for Diversity)
  # ==========================================================================
  - name: "Security & Vulnerabilities"
    priority: 1
    weight: 1.0
    max_items: 5
    output_sections:
      - "security_alerts"
      - "top_signals"  # High-impact CVEs go here

    search_strategy:
      order: 1  # Search FIRST
      queries:
        - '"CVE" site:nvd.nist.gov OR site:github.com/advisories'
        - '"npm vulnerability" OR "golang security" OR "php security"'
        - '"CVSS" AND ("npm" OR "golang" OR "composer")'
      time_window: "24-72h"  # Broader window for security
      required_for_diversity: true

    sources:
      primary:
        - name: "NVD - National Vulnerability Database"
          url: "https://nvd.nist.gov/vuln"
          domains: ["nvd.nist.gov"]

        - name: "GitHub Advisory Database"
          url: "https://github.com/advisories"
          domains: ["github.com/advisories"]

        - name: "CISA Known Exploited Vulnerabilities"
          url: "https://www.cisa.gov/known-exploited-vulnerabilities-catalog"
          domains: ["cisa.gov"]

      secondary:
        - name: "Tenable CVE Feeds"
          url: "https://www.tenable.com/cve"

    extract:
      - "CVE numbers with CVSS scores (especially >7.0)"
      - "Affected versions for npm, golang, php, composer packages"
      - "Exploitation status (in-the-wild vs theoretical)"
      - "Fix availability and patch versions"
      - "AWS service vulnerabilities"

    keywords:
      boost: ["CVE", "CVSS", "exploit", "vulnerability", "npm", "golang", "php", "composer", "NestJS", "TypeScript"]
      filter: ["nestjs", "express", "typescript", "golang", "php", "aws"]

  # ==========================================================================
  # 2. DEVELOPER EXPERIENCE & PLATFORM ENGINEERING
  # ==========================================================================
  - name: "Developer Experience & Platform Engineering"
    priority: 2
    weight: 0.9
    max_items: 5
    output_sections:
      - "developer_experience"
      - "top_signals"  # Major releases/patterns go here

    search_strategy:
      order: 2  # Search SECOND
      queries:
        - '"Backstage" site:backstage.io OR site:backstage.spotify.com'
        - '"CNCF" site:cncf.io OR "Kubernetes" OR "platform engineering"'
        - 'site:infoq.com OR site:thenewstack.io "developer experience"'
      time_window: "48-72h"
      required_for_diversity: true

    sources:
      primary:
        - name: "Backstage"
          url: "https://backstage.io/blog/"
          domains: ["backstage.io", "backstage.spotify.com"]
          rss: "https://backstage.spotify.com/discover/blog/rss.xml"

        - name: "CNCF"
          url: "https://www.cncf.io/blog/"
          domains: ["cncf.io"]
          rss: "https://www.cncf.io/feed/"

        - name: "InfoQ"
          url: "https://www.infoq.com/news/"
          domains: ["infoq.com"]
          rss: "https://feed.infoq.com/"

        - name: "The New Stack"
          url: "https://thenewstack.io/"
          domains: ["thenewstack.io"]
          rss: "https://thenewstack.io/feed/"

      secondary:
        - name: "ThoughtWorks Tech Radar"
          url: "https://www.thoughtworks.com/radar"

    extract:
      - "Backstage releases and feature updates"
      - "CNCF project maturity announcements"
      - "Platform engineering patterns and golden paths"
      - "Developer portal updates"
      - "DevOps and AIOps tool improvements"

    keywords:
      boost: ["Backstage", "CNCF", "platform engineering", "golden path", "developer portal", "DORA", "AIOps"]

  # ==========================================================================
  # 3. HEALTHTECH REGULATION & INTEROPERABILITY
  # ==========================================================================
  - name: "Healthtech Regulation & Interoperability"
    priority: 2
    weight: 0.9
    max_items: 5
    output_sections:
      - "ai_trends"  # Regulatory AI items
      - "top_signals"  # Dated obligations/deadlines

    search_strategy:
      order: 3  # Search THIRD
      queries:
        - '"FHIR" site:hl7.org OR site:digital.nhs.uk'
        - '"NHS" OR "MHRA" OR "FDA" site:gov.uk OR site:fda.gov'
        - '"EU AI Act" OR "SaMD" OR "medical device"'
      time_window: "48-72h"
      required_for_diversity: true

    sources:
      primary:
        - name: "HL7 Blog"
          url: "https://blog.hl7.org/"
          domains: ["blog.hl7.org", "hl7.org"]
          rss: "https://blog.hl7.org/rss.xml"

        - name: "NHS Digital FHIR APIs"
          url: "https://digital.nhs.uk/services/fhir-apis"
          domains: ["digital.nhs.uk"]

        - name: "FDA AI/ML SaMD"
          url: "https://www.fda.gov/medical-devices/software-medical-device-samd/artificial-intelligence-and-machine-learning-software-medical-device"
          domains: ["fda.gov"]

        - name: "MHRA"
          url: "https://www.gov.uk/mhra"
          domains: ["gov.uk/mhra"]
          rss: "https://yellowcard.mhra.gov.uk/news/rss"

        - name: "EU AI Act"
          url: "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai"
          domains: ["ec.europa.eu"]

      secondary:
        - name: "ONC Health IT"
          url: "https://www.healthit.gov/buzz-blog/"
          rss: "https://www.healthit.gov/buzz-blog/feed"

    extract:
      - "FHIR ballot updates and implementation guides"
      - "NHS API changes and interoperability guidance"
      - "Regulatory deadlines with specific dates"
      - "EU AI Act timeline and obligations"
      - "FDA/MHRA SaMD guidance updates"
      - "HL7 working group decisions"

    keywords:
      boost: ["FHIR", "HL7", "NHS", "MHRA", "EMA", "FDA", "SaMD", "GDPR", "HIPAA", "EU AI Act", "interoperability", "TEFCA"]

  # ==========================================================================
  # 4. AWS PLATFORM & SERVERLESS (Lower Priority Due to Saturation)
  # ==========================================================================
  - name: "AWS Platform & Serverless"
    priority: 4  # Lower priority - search LAST
    weight: 0.7  # Lower weight due to diversity requirements
    max_items: 10  # More items allowed, but most go to aws_platform_changes
    output_sections:
      - "aws_platform_changes"
      - "top_signals"  # MAX 1 item here (ultra-strict cap)

    search_strategy:
      order: 5  # Search LAST (after all non-AWS categories)
      queries:
        - "site:aws.amazon.com What's New OR pricing OR security bulletin"
        - "site:aws.amazon.com/blogs/compute OR site:aws.amazon.com/blogs/architecture"
      time_window: "24-48h"  # Narrower window
      required_for_diversity: false  # Not required
      max_in_top_signals: 1  # STRICT CAP

    sources:
      primary:
        - name: "AWS What's New"
          url: "https://aws.amazon.com/new/"
          domains: ["aws.amazon.com"]
          rss: "https://aws.amazon.com/about-aws/whats-new/recent/feed/"

        - name: "AWS Security Bulletins"
          url: "https://aws.amazon.com/security/security-bulletins/"
          domains: ["aws.amazon.com"]
          rss: "https://aws.amazon.com/security/security-bulletins/feed/"

        - name: "AWS Compute Blog"
          url: "https://aws.amazon.com/blogs/compute/"
          domains: ["aws.amazon.com"]
          rss: "https://aws.amazon.com/blogs/compute/feed/"

        - name: "AWS Architecture Blog"
          url: "https://aws.amazon.com/blogs/architecture/"
          domains: ["aws.amazon.com"]
          rss: "https://aws.amazon.com/blogs/architecture/feed/"

      secondary:
        - name: "Serverless Land"
          url: "https://serverlessland.com/"
          rss: "https://serverlessland.com/feed.xml"

        - name: "CNCF"
          url: "https://www.cncf.io/"

    extract:
      - "Lambda, API Gateway, EventBridge, Step Functions, DynamoDB updates"
      - "Pricing changes with customer impact"
      - "Security bulletins and behavior changes"
      - "Well-Architected framework updates"
      - "ONLY high-impact items for top_signals (outages, pricing, security)"

    keywords:
      boost: ["Lambda", "API Gateway", "EventBridge", "Step Functions", "DynamoDB", "EKS", "pricing", "security bulletin", "Well-Architected", "eu-west-2"]

    placement_rules:
      top_signals: "ONLY pricing/behavior/security changes, outages with primary source"
      aws_platform_changes: "Routine What's New, GAs, region support, console toggles"

  # ==========================================================================
  # 5. CORPORATE COMPETITORS
  # ==========================================================================
  - name: "Corporate Competitors"
    priority: 3
    weight: 0.8
    max_items: 5
    output_sections:
      - "corporate_competitors"
      - "top_signals"  # Earnings/major moves go here

    search_strategy:
      order: 4  # Search before AWS
      queries:
        - '"Hims" OR "Hims & Hers" site:investors.hims.com'
        - '"Doctolib" OR "Teladoc" OR "Zava"'
        - '"healthtech earnings" OR "digital health"'
      time_window: "48-72h"
      required_for_diversity: false  # Optional but preferred

    sources:
      primary:
        - name: "Hims & Hers Investor Relations"
          url: "https://investors.hims.com/news/default.aspx"
          domains: ["investors.hims.com"]

        - name: "SEC EDGAR (CIK 0001773751)"
          url: "https://www.sec.gov/edgar/search/"
          domains: ["sec.gov"]

      secondary:
        - name: "Doctolib"
          url: "https://www.doctolib.com/"

        - name: "Teladoc"
          url: "https://teladochealth.com/"

        - name: "Zava"
          url: "https://www.zavamed.com/uk/"

    extract:
      - "Earnings announcements and guidance"
      - "Product launches and service expansions"
      - "Subscriber metrics and market strategy"
      - "SEC filings and material events"
      - "Competitive pricing and regulatory changes"

    keywords:
      boost: ["Hims", "Doctolib", "Teladoc", "Zava", "Babylon", "earnings", "SEC filing"]

  # ==========================================================================
  # 6. AI TRENDS (Clinical & Platform)
  # ==========================================================================
  - name: "AI Trends"
    priority: 3
    weight: 0.8
    max_items: 2  # Stricter cap unless dated obligation
    output_sections:
      - "ai_trends"
      - "top_signals"  # Regulatory AI with dates

    search_strategy:
      order: 3  # Part of healthtech search
      queries:
        - 'site:ai.nejm.org OR site:nature.com/npjdigitalmed'
        - '"AWS Bedrock" OR "OpenAI" OR "Anthropic" platform'
        - '"clinical AI" OR "medical AI" OR "healthcare AI"'
      time_window: "48-72h"
      required_for_diversity: false

    sources:
      primary:
        - name: "NEJM AI"
          url: "https://ai.nejm.org/"
          domains: ["ai.nejm.org"]
          rss: "https://ai.nejm.org/feeds/latest.rss"

        - name: "npj Digital Medicine"
          url: "https://www.nature.com/npjdigitalmed/"
          domains: ["nature.com"]
          rss: "https://www.nature.com/npjdigitalmed.rss"

        - name: "Lancet Digital Health"
          url: "https://www.thelancet.com/journals/landig/home"
          domains: ["thelancet.com"]
          rss: "https://www.thelancet.com/content/rss"

      secondary:
        - name: "OpenAI"
          url: "https://openai.com/news/"
          rss: "https://openai.com/news/rss.xml"

        - name: "Hugging Face"
          url: "https://huggingface.co/blog"
          rss: "https://huggingface.co/blog/feed.xml"

    extract:
      - "Regulatory guidance with effective dates"
      - "Clinical AI safety standards"
      - "Platform-impacting infra/tooling only"
      - "Model serving and observability"

    keywords:
      boost: ["Bedrock", "model serving", "observability", "guardrails", "GPU", "clinical AI", "medical AI"]

# ----------------------------------------------------------------------------
# SEVERITY & IMPACT CLASSIFICATION
# ----------------------------------------------------------------------------
severity_rules:
  high:
    - "compliance deadline"
    - "regulatory obligation"
    - "breaking change"
    - "exploited vulnerability"
    - "critical security"
    - "AWS service deprecation"
    - "major cost impact"
    - "pricing change"
    - "outage"
    - "AI Act"
    - "SaMD"
    - "CVSS >7.0"

  medium:
    - "new feature"
    - "ecosystem shift"
    - "version upgrade"
    - "recommended update"
    - "guidance"
    - "release"

  low:
    - "advisory"
    - "background trend"
    - "minor update"

impact_keywords:
  Regulatory:
    - "compliance"
    - "regulation"
    - "GDPR"
    - "HIPAA"
    - "FDA"
    - "MHRA"
    - "AI Act"
    - "SaMD"
    - "medical device"

  Platform:
    - "AWS"
    - "Lambda"
    - "architecture"
    - "infrastructure"
    - "deployment"
    - "serverless"

  Security:
    - "CVE"
    - "vulnerability"
    - "security"
    - "exploit"
    - "patch"
    - "advisory"

  DX:
    - "developer experience"
    - "tooling"
    - "productivity"
    - "workflow"
    - "backstage"
    - "golden path"

  Cost:
    - "pricing"
    - "cost"
    - "optimization"
    - "savings"
    - "budget"

  "Org/Strategy":
    - "strategy"
    - "organizational"
    - "M&A"
    - "earnings"
    - "acquisition"

  Healthtech:
    - "FHIR"
    - "HL7"
    - "NHS"
    - "interoperability"
    - "clinical"
