# Me2resh Daily Intel Scan - Comprehensive RSS Source Catalogue
# RSS-first approach: Only includes sources with working RSS/Atom feeds
# Last updated: 2025-10-19

email:
  to_address: "${TO_EMAIL_ADDRESS}"
  from_address: "${FROM_EMAIL_ADDRESS}"
  subject_prefix: "Me2resh Daily"

scan_config:
  timezone: "Europe/London"
  scan_time: "05:00"
  lookback_hours: 72  # 72-hour freshness window
  max_items_per_source: 20  # Limit items per source to control costs
  enable_perplexity_research: true  # Enable Perplexity for additional coverage

topics:
  # ============================================================================
  # 1. AI IN HEALTHCARE & CLINICAL PATHWAYS
  # ============================================================================
  - name: "AI Healthcare - Clinical Journals"
    category: "ai_healthcare"
    priority: 1
    sources:
      - name: "NEJM AI"
        url: "https://ai.nejm.org/"
        rss_url: "https://ai.nejm.org/feeds/latest.rss"
        type: "rss"

      - name: "npj Digital Medicine"
        url: "https://www.nature.com/npjdigitalmed/"
        rss_url: "https://www.nature.com/npjdigitalmed.rss"
        type: "rss"

      - name: "The Lancet Digital Health"
        url: "https://www.thelancet.com/journals/landig/home"
        rss_url: "https://www.thelancet.com/content/rss"
        type: "rss"

  - name: "AI Platforms & Vendors"
    category: "ai_platform"
    priority: 1
    sources:
      - name: "OpenAI News"
        url: "https://openai.com/news/"
        rss_url: "https://openai.com/news/rss.xml"
        type: "rss"

      - name: "Hugging Face Blog"
        url: "https://huggingface.co/blog"
        rss_url: "https://huggingface.co/blog/feed.xml"
        type: "rss"

      - name: "AWS Machine Learning Blog"
        url: "https://aws.amazon.com/blogs/machine-learning/"
        rss_url: "https://feeds.feedburner.com/AmazonWebServicesBlogMachineLearning"
        type: "rss"

  # ============================================================================
  # 2. AWS & SERVERLESS PLATFORM
  # ============================================================================
  - name: "AWS Official Feeds"
    category: "aws_platform"
    priority: 1
    sources:
      - name: "AWS What's New"
        url: "https://aws.amazon.com/new/"
        rss_url: "https://aws.amazon.com/about-aws/whats-new/recent/feed/"
        type: "rss"

      - name: "AWS Security Bulletins"
        url: "https://aws.amazon.com/security/security-bulletins/"
        rss_url: "https://aws.amazon.com/security/security-bulletins/feed/"
        type: "rss"

      - name: "AWS Compute Blog"
        url: "https://aws.amazon.com/blogs/compute/"
        rss_url: "https://aws.amazon.com/blogs/compute/feed/"
        type: "rss"

      - name: "AWS Architecture Blog"
        url: "https://aws.amazon.com/blogs/architecture/"
        rss_url: "https://aws.amazon.com/blogs/architecture/feed/"
        type: "rss"

      - name: "Lambda Release Notes"
        url: "https://docs.aws.amazon.com/lambda/latest/dg/lambda-updates.html"
        rss_url: "https://docs.aws.amazon.com/lambda/latest/dg/lambda-updates.rss"
        type: "rss"

      - name: "CloudFormation Release Notes"
        url: "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html"
        rss_url: "https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.rss"
        type: "rss"

  - name: "Serverless Ecosystem"
    category: "serverless"
    priority: 2
    sources:
      - name: "Serverless Land"
        url: "https://serverlessland.com/"
        rss_url: "https://serverlessland.com/feed.xml"
        type: "rss"

      - name: "Serverless Framework Blog"
        url: "https://www.serverless.com/blog"
        rss_url: "https://www.serverless.com/blog/rss"
        type: "rss"

      - name: "CNCF Blog"
        url: "https://www.cncf.io/blog/"
        rss_url: "https://www.cncf.io/feed/"
        type: "rss"

  # ============================================================================
  # 3. FHIR / HL7 / INTEROPERABILITY
  # ============================================================================
  - name: "FHIR & HL7 Standards"
    category: "fhir_standards"
    priority: 2
    sources:
      - name: "HL7 Blog"
        url: "https://blog.hl7.org/"
        rss_url: "https://blog.hl7.org/rss.xml"
        type: "rss"

      - name: "Hay on FHIR (Community Blog)"
        url: "https://fhirblog.com/"
        rss_url: "https://fhirblog.com/feed/"
        type: "rss"

      - name: "ONC Health IT Buzz"
        url: "https://www.healthit.gov/buzz-blog/"
        rss_url: "https://www.healthit.gov/buzz-blog/feed"
        type: "rss"

  # ============================================================================
  # 4. SECURITY ADVISORIES
  # ============================================================================
  - name: "Security & Vulnerabilities"
    category: "security"
    priority: 1
    sources:
      - name: "CVE Details - Latest CVEs"
        url: "https://www.cvedetails.com/"
        rss_url: "https://www.cvedetails.com/vulnerability-feeds-form.php"
        type: "rss"

      - name: "Tenable CVE Feeds"
        url: "https://www.tenable.com/cve"
        rss_url: "https://www.tenable.com/cve/feeds/newest"
        type: "rss"

  # ============================================================================
  # 5. STACK RELEASES (GitHub Atom Feeds)
  # ============================================================================
  - name: "Language & Framework Releases"
    category: "releases"
    priority: 2
    sources:
      - name: "NestJS Releases"
        url: "https://github.com/nestjs/nest/releases"
        rss_url: "https://github.com/nestjs/nest/releases.atom"
        type: "rss"

      - name: "TypeScript Releases"
        url: "https://github.com/microsoft/TypeScript/releases"
        rss_url: "https://github.com/microsoft/TypeScript/releases.atom"
        type: "rss"

      - name: "Go Blog"
        url: "https://go.dev/blog/"
        rss_url: "https://go.dev/blog/feed.atom"
        type: "rss"

      - name: "AWS SAM CLI Releases"
        url: "https://github.com/aws/aws-sam-cli/releases"
        rss_url: "https://github.com/aws/aws-sam-cli/releases.atom"
        type: "rss"

      - name: "AWS SAM Model Releases"
        url: "https://github.com/aws/serverless-application-model/releases"
        rss_url: "https://github.com/aws/serverless-application-model/releases.atom"
        type: "rss"

      - name: "PHP Security Advisories"
        url: "https://github.com/php/php-src/security/advisories"
        rss_url: "https://github.com/php/php-src/security/advisories.atom"
        type: "rss"

  # ============================================================================
  # 6. DEVELOPER EXPERIENCE & TRENDS
  # ============================================================================
  - name: "Developer Experience"
    category: "developer_experience"
    priority: 3
    sources:
      - name: "Backstage Spotify Blog"
        url: "https://backstage.spotify.com/discover/blog/"
        rss_url: "https://backstage.spotify.com/discover/blog/rss.xml"
        type: "rss"

      - name: "InfoQ News"
        url: "https://www.infoq.com/news/"
        rss_url: "https://feed.infoq.com/"
        type: "rss"

      - name: "The New Stack"
        url: "https://thenewstack.io/"
        rss_url: "https://thenewstack.io/feed/"
        type: "rss"

  # ============================================================================
  # 7. INTERNATIONAL REGULATORS (RSS-enabled)
  # ============================================================================
  - name: "Healthcare Regulators"
    category: "regulatory"
    priority: 2
    sources:
      - name: "MHRA Yellow Card News"
        url: "https://yellowcard.mhra.gov.uk/news"
        rss_url: "https://yellowcard.mhra.gov.uk/news/rss"
        type: "rss"

      - name: "EMA RSS Feeds"
        url: "https://www.ema.europa.eu/en/news-events/rss-feeds"
        rss_url: "https://www.ema.europa.eu/en/news-events/rss-feeds"
        type: "rss"

      - name: "IMDRF RSS"
        url: "https://www.imdrf.org/"
        rss_url: "https://www.imdrf.org/rss-feeds"
        type: "rss"

      - name: "HAS (France) RSS"
        url: "https://www.has-sante.fr/"
        rss_url: "https://www.has-sante.fr/jcms/c_1771214/fr/nos-flux-d-information-rss"
        type: "rss"

      - name: "ANSM (France) RSS"
        url: "https://ansm.sante.fr/"
        rss_url: "https://ansm.sante.fr/page/flux-rss"
        type: "rss"

      - name: "CMS RSS Hub"
        url: "https://www.cms.gov/"
        rss_url: "https://www.cms.gov/about-cms/web-policies-important-links/rss-feeds"
        type: "rss"

# Severity rules for automatic classification
severity_rules:
  high:
    - "compliance deadline"
    - "regulatory obligation"
    - "breaking change"
    - "exploited vulnerability"
    - "critical security"
    - "AWS service deprecation"
    - "major cost impact"
    - "AI Act"
    - "SaMD"

  medium:
    - "new feature"
    - "ecosystem shift"
    - "version upgrade"
    - "recommended update"
    - "guidance"

  low:
    - "advisory"
    - "background trend"
    - "minor update"

# Impact mapping keywords
impact_keywords:
  Regulatory:
    - "compliance"
    - "regulation"
    - "GDPR"
    - "HIPAA"
    - "FDA"
    - "MHRA"
    - "AI Act"
    - "SaMD"
    - "medical device"

  Platform:
    - "AWS"
    - "Lambda"
    - "architecture"
    - "infrastructure"
    - "deployment"
    - "serverless"

  Security:
    - "CVE"
    - "vulnerability"
    - "security"
    - "exploit"
    - "patch"
    - "advisory"

  DX:
    - "developer experience"
    - "tooling"
    - "productivity"
    - "workflow"
    - "backstage"

  Cost:
    - "pricing"
    - "cost"
    - "optimization"
    - "savings"
    - "budget"

  "Org/Strategy":
    - "strategy"
    - "organizational"
    - "M&A"
    - "earnings"
    - "acquisition"

# Perplexity Research Query (Combined single query for all topics)
perplexity_research:
  combined_query: |
    Research the following topics for updates in the last 72 hours. For each topic, provide specific article titles, URLs, and publication dates.

    Topics to research:

    1. AI in Healthcare & Clinical AI:
       - NEJM AI, npj Digital Medicine, Lancet Digital Health new publications
       - FDA AI/ML SaMD guidance updates and draft guidance documents
       - MHRA Software & AI as Medical Device regulatory updates
       - EU AI Act timeline updates, GPAI obligations, high-risk medical device classifications
       - Clinical AI safety standards, validation frameworks, monitoring requirements

    2. FHIR, HL7, and Healthcare Interoperability:
       - HL7 FHIR ballot updates, implementation guides, new specifications
       - NHS England Digital FHIR API changes and interoperability guidance
       - ONC TEFCA FHIR roadmap updates and exchange requirements
       - CMS FHIR spotlight initiatives and burden reduction programs
       - HL7 UK implementations and UK-specific FHIR guidance

    3. AWS Platform & Serverless:
       - AWS Lambda, API Gateway, EventBridge, Step Functions, DynamoDB updates
       - AWS security bulletins, ALAS (Amazon Linux Security Advisories)
       - AWS Compute Blog, Architecture Blog, Well-Architected updates
       - Serverless ecosystem: CNCF, Kubernetes, serverless frameworks
       - AWS SAM CLI and SAM specification releases

    4. Security & Vulnerabilities:
       - Critical CVEs affecting TypeScript/NestJS (npm ecosystem)
       - Golang security advisories and vulnerabilities
       - PHP security updates and advisories
       - AWS service vulnerabilities and security patches
       - CISA Known Exploited Vulnerabilities (KEV) catalog updates
       - GitHub Advisory Database for npm, Go, PHP

    5. Corporate Intelligence - Hims & Hers:
       - Hims & Hers Health Inc (CIK 0001773751) recent news
       - SEC filings: 10-K, 10-Q, 8-K, Form 144
       - Earnings announcements, financial guidance, subscriber metrics
       - Product launches, service expansions, market strategy
       - UK Competitors: Zava (zavamed.com) and ASDA Online Doctor updates
       - Competitive pricing, new treatment offerings, regulatory changes

    6. Developer Experience & Platform Engineering:
       - Backstage (Spotify) developer portal updates and patterns
       - InfoQ, The New Stack platform engineering trends
       - CNCF projects reaching maturity/GA relevant to serverless
       - ThoughtWorks Technology Radar platform/DX signals
       - DevOps, AIOps, golden path improvements

    7. Language & Framework Releases:
       - NestJS releases and breaking changes
       - TypeScript releases and language features
       - Golang releases and standard library updates
       - AWS SAM CLI and model specification updates
       - PHP security releases and version updates

    For each update found, provide:
    - Exact article title
    - Full URL to the source
    - Publication date (YYYY-MM-DD format)
    - Brief one-sentence summary

    Focus on official sources, primary documentation, and regulatory agencies. Include specific dates for compliance deadlines and effective dates.
